### PR TITLE
Fix NA error

### PR DESCRIPTION
**Pull request by rpoetrap**
# PR Details

Fix NA error

## Description

Fix NA error

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by xuri — CHANGES_REQUESTED** [review]
Thanks for your pull request. The second parameter of the `newErrorFormulaArg` function represents the error message, which is used to explain the error string. I purpose making the result of the `CalcCellValue` function an error string, and the error message of that as the error value. What do you think about that?

**Comment by rpoetrap** [comment]
I had this problem when trying to use this formula `=IFNA(VLOOKUP(...), ...)`, i thought this problem caused by the Error value in formulaArg is not `#N/A`?
or should I change the condition in `IFNA` function from `arg.Value() == formulaErrorNA` to `arg.String == formulaErrorNA`?

**Review by xuri — COMMENTED** [review]
I means that using formula error string in the result of the `CalcCellValue` function when error occurs, and using the error message in the `CalcCellValue` function returns error. I have a changes for all formula functions and updates the unit tests based on your branch. For example:

```go
result, err := f.CalcCellValue("Sheet1", "A1")
// Now, the variable 'result' was not empty when the error occurs
// result: "#N/A"
// err: "HLOOKUP no result found"
```

**Comment by rpoetrap** [comment]
Oh that's perfect, btw I just added a fix to the IFNA function.

**Review by xuri — APPROVED** [review]

**Review by xuri — APPROVED** [review]
LGTM. Thanks for your contribution.

**Pull request merged**
