### PR TITLE
fix shared formula incorrect (#844)

### PR DESCRIPTION
**Pull request by raochq**
fix shared formula incorrect (#844)

### CODE REVIEW

**Comment by jaby** [comment]
@xuri Any chance this pull request will be accepted soon?  I've tried it out and it fixes a problem with a shared formula in the same worksheet.  In my case it concerns a range where the first row's B-column-formula  (B1) is returned for each of the following rows, resulting in the wrong B3, B4 etc cell calculation. 
Thanks in advance!

And thanks @raochq for the solution!

**Comment by xuri** [comment]
I need some time to review this PR.

**Comment by cwouyang** [comment]
> 
> 
> I need some time to review this PR.

Hi @xuri, any progress? I encountered same issue and needed this MR as well 🥺

**Review by xuri — COMMENTED** [review]
Hi @raochq, thanks for your contribution. I have committed some changes base on your branch, in this commit:

- Separate sub function `parseSharedFormula` reduce cyclomatic complexities
- Make `SplitCellName` support absolute cell coordinates, and remove the `CellNameToCoordinates2`, `CellNameToCoordinates` is 2x faster and less memeory allocation than `CellNameToCoordinates2`
- Add unit test for the function `GetCellFormula`

**Pull request merged**
