### PR TITLE
Update checkSheet GetTables error: index out of range

### PR DESCRIPTION
**Pull request by lujin1**
# PR Details

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by lujin1** [comment]
When the sheet does not start with table, an error will be reported when getting tables.

**Review by xuri — CHANGES_REQUESTED** [review]
Thanks for your PR. Could you add unit tests for this changes?

**Comment by tumbleweedd** [comment]
> When the sheet does not start with table, an error will be reported when getting tables.

Could you please provide the test file that caused the panic? I will be very grateful

**Comment by xuri** [comment]
Hi @tumbleweedd, I have already analytics and created a the special case workbook file can be reproduce this problem, but the fix in this changes will be cause the some cell value was missing, I think we need to made some change based on this.

**Review by xuri — APPROVED** [review]
LGTM. Thanks for your contribution. I have made some changes based on your branch. This feature will be released in the next version.

**Comment by xuri** [comment]
According to [the benchmark report](https://github.com/xuri/excelize/wiki#performance-figures) of v2.8.1, the fix slows down the get rows about 3 times, and memory using about 17 times. We need to fixed the performance impact later.

**Pull request merged**
