### PR TITLE
Add GetRows to retrieve unformatted cell values

### PR DESCRIPTION
**Pull request by tgulacsi**
This allows converting to time.Time without goint throguh the formatting and parsing steps.
Use the stored floating point number insted.

The only remaining step is a helper that decides whether the cell is a date or not (sth. like `File.Styles.CellXfs.Xf[cell.S].NumFmtID IN (14, 15, 16, 17, 22)`).

## Checklist

- [x] My code follows the code style of this project.
- [-] My change requires a change to the documentation.
- [-] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [-] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tgulacsi** [comment]
Shall I update this? Is there any possibility that this may be merged or at least reviewed?

**Comment by tgulacsi** [comment]
Hi @xuri, shall I update this?

**Comment by xuri** [comment]
Hi @tgulacsi, thanks for your PR. I need some time to review.

**Comment by xuri** [comment]
Hi @tgulacsi thanks for your PR, and sorry for my so late reply. I suggest adding an option for columns and rows iterator, to support specified if apply number format, instead of adding the new function `RawColumns`, so I'll close this.

**Comment by tgulacsi** [comment]
Ok, I can add a "rawValues bool" to Cols, Rows, rowsXMLIterator & co. structs, but how to allow setting these parameters?
Export them, or add a "SetRawOption(bool)" method to them?

**Comment by xuri** [comment]
Hi @tgulacsi, I've added optional parameters for the  `GetCellValue`, `GetRows`, `GetCols`, `Rows`, and `Cols`, to support specific read cells with raw value, please try upgrade to the master branch. For example, disable apply number format on get rows:

```go
rows, err := f.GetRows("Sheet1", excelize.Options{RawCellValue: true})
```

**Comment by tgulacsi** [comment]
Thanks, that's perfect!

**Pull request closed without merging**
