### PR TITLE
This fixed: type number format be saved as a string by SetCellValue. …

### PR DESCRIPTION
**Pull request by keepstep**
# PR Details
This fixed: type number format be saved as a string by SetCellValue. 
eg: 
type Number int
SetCellValue( s , A1, Number(10))
SetCellValue( s , A2, Number(10))
SetCellFormula( s, A3,  "SUM(A1,A2)")

result:
A1,A2  be save as a string:  '10 
A3 is 0 if you open the file

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by xuri — COMMENTED** [review]
Thanks for your pull request, but I don't know what bug this fixes. I have tested as following with the master branch code to set cell values and formulas, and it works well. Could you provide more details for that, and show us a complete, standalone example program or reproducible demo?

```go
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	f := excelize.NewFile()
	defer func() {
		// Close the spreadsheet.
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	if err := f.SetCellValue("Sheet1", "A1", 10); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SetCellValue("Sheet1", "A2", 10); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SetCellFormula("Sheet1", "A3", "SUM(A1,A2)"); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

**Review by xuri — COMMENTED** [review]
Thanks for your pull request, but I don't know what bug this fixes. I have tested as following with the master branch code to set cell values and formulas, and it works well. Could you provide more details for that, and show us a complete, standalone example program or reproducible demo?

**Comment by keepstep** [comment]
type Number int
you can try it 

```golang
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)
type Number int
func main() {
	f := excelize.NewFile()
	defer func() {
		// Close the spreadsheet.
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	var value Number = 10
	if err := f.SetCellValue("Sheet1", "A1", value); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SetCellValue("Sheet1", "A2", value); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SetCellFormula("Sheet1", "A3", "SUM(A1,A2)"); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

**Review by xuri — COMMENTED** [review]
Thanks for your feedback. As the documentation of the `SetCellValue` function says, this function only supports the Go language's basic data types. Users should covert cell values from data type alias or nested data type alias to Go language basic data types by themselves like this:

```diff
-   if err := f.SetCellValue("Sheet1", "A1", value); err != nil {
+   if err := f.SetCellValue("Sheet1", "A1", int(value)); err != nil {
```

So I don't suggest introducing this feature support.

**Comment by keepstep** [comment]
ok ,i understood.
maybe using generic to constrain inputs is a better to avoid irregular param

**Comment by xuri** [comment]
The issue #1546 talk about generic supports. I closed this PR, if you have any question, please let me know, and you can reopen this anytime.

**Pull request closed without merging**
