### PR TITLE
Use a faster deepcopy library

### PR DESCRIPTION
**Pull request by Juneezee**
# PR Details

## Related Issue

Closes https://github.com/qax-os/excelize/issues/2029.

## Motivation and Context

Benchmark:

```go
package excelize

import (
	"testing"

	olddeepcopy "github.com/mohae/deepcopy"
	newdeepcopy "github.com/tiendc/go-deepcopy"
)

func BenchmarkCopyXlsxCol(b *testing.B) {
	src := xlsxCol{}

	b.Run("old", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			olddeepcopy.Copy(src)
		}
	})

	b.Run("new", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			var dst xlsxCol
			newdeepcopy.Copy(&dst, src)
		}
	})
}

func BenchmarkCopyXlsxRow(b *testing.B) {
	src := xlsxRow{}

	b.Run("old", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			olddeepcopy.Copy(src)
		}
	})

	b.Run("new", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			var dst xlsxRow
			newdeepcopy.Copy(&dst, src)
		}
	})
}

func BenchmarkCopyXlsxWorksheet(b *testing.B) {
	f, err := prepareTestBook1()
	if err != nil {
		b.Fatal(err)
	}

	idx, err := f.NewSheet("CopySheet")
	if err != nil {
		b.Fatal(err)
	}

	fromSheet := f.GetSheetName(idx)
	src, err := f.workSheetReader(fromSheet)
	if err != nil {
		b.Fatal(err)
	}

	b.Run("old", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			olddeepcopy.Copy(src)
		}
	})

	b.Run("new", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			var dst xlsxWorksheet
			newdeepcopy.Copy(&dst, src)
		}
	})
}
```

Result:

```
goos: linux
goarch: amd64
pkg: github.com/xuri/excelize/v2
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkCopyXlsxCol/old-16      	  446193	      2483 ns/op	     224 B/op	      13 allocs/op
BenchmarkCopyXlsxCol/new-16      	  963056	      1148 ns/op	     128 B/op	       3 allocs/op
BenchmarkCopyXlsxRow/old-16      	  344492	      3135 ns/op	     344 B/op	      16 allocs/op
BenchmarkCopyXlsxRow/new-16      	  909142	      1371 ns/op	     192 B/op	       3 allocs/op
BenchmarkCopyXlsxWorksheet/old-16         	   49108	     23097 ns/op	    3656 B/op	     128 allocs/op
BenchmarkCopyXlsxWorksheet/new-16         	  176534	      7085 ns/op	     808 B/op	       6 allocs/op
PASS
ok  	github.com/xuri/excelize/v2	7.377s
```

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by xuri — APPROVED** [review]
LGTM, thanks for your contribution.

**Comment by xuri** [comment]
Thanks for your comments, although the new deepcopy library not popular and not widely used currently, but after I checked the code of that, it seems fine. I think if bug reports before next release of excelize, we can revert this or using encoding/gob for deepcopy. @Juneezee what you think of this?

**Comment by Juneezee** [comment]
Hi @arp242, thank you for your feedback and concerns. I did review the source code of the suggested library before making the proposal in https://github.com/qax-os/excelize/issues/2029.

> The previous library was unmaintained, but it was simple, worked, and was trusted. This is a random project from more or less a random person without any reputation that I can see.

You’re correct that the previous library code is simpler. However, the new library also includes unit tests to ensure functionality. Are your main concerns related to the security or trustworthiness of the code?

> The benchmarks didn't really demonstrate this makes a meaningful difference.

The performance improvement is most noticeable in the Copy Worksheet function. For the benchmark, I used a small worksheet from the test Excel file (containing only two charts and a few rows and columns with data). Even with this relatively simple example, we see significant improvements in execution time and memory allocations. These benefits will scale and become even more impactful when working with larger worksheets.

**Comment by Juneezee** [comment]
> Thanks for your comments, although the new deepcopy library not popular and not widely used currently, but after I checked the code of that, it seems fine. I think if bug reports before next release of excelize, we can revert this or using encoding/gob for deepcopy. @Juneezee what you think of this?

@xuri I agree. This PR introduces only a small number of code changes. If it leads to any new bugs or regressions, we can easily revert to the previous library.

**Comment by shcabin** [comment]
> 有人审计过这个图书馆吗？
> 
> 之前的库无人维护，但它简单、可用且值得信赖。这是一个随机项目，几乎出自一个毫无名气的随机开发者之手。虽然我 99% 确定它没问题，但并非 100%。我不太愿意把它引入到我们的依赖关系树中。
> 
> 我们这里讨论的是纳秒级。基准测试并没有真正证明这会带来什么显著的差异。


I have identified a potential issue where this library cannot handle DeepCopy of sync.Map, will return an ErrTypeNonCopyable error. And the code here did not handle any errors

**Comment by shcabin** [comment]
here: https://go.dev/play/p/DcHjMRGjklT

**Comment by Juneezee** [comment]
> I have identified a potential issue where this library cannot handle DeepCopy of sync.Map, will return an ErrTypeNonCopyable error. And the code here did not handle any errors

@shcabin Thanks for reporting the issue. I have reported the issue to library author here: https://github.com/tiendc/go-deepcopy/issues/34.

**Pull request merged**
