### PR TITLE
Preserve whitespace in cells

### PR DESCRIPTION
**Pull request by Arnie97**
# PR Details

## Description
This patch backports the more reasonable whitespace detection condition from `SetCellRichText()` to `setSharedString()`.

## Related Issue
#69, #269

## Motivation and Context

A relevant formatting fix was first introduced in `setSharedString()` in dc012645. Unfortunately, a strict condition was applied, so the patch only fixed formatting for the cells with prefix and trailing spaces, not the ones with line ending characters:

```go
t := xlsxT{Val: val}
// Leading and ending space(s) character detection.
if len(val) > 0 && (val[0] == 32 || val[len(val)-1] == 32) {
	ns := xml.Attr{
		Name:  xml.Name{Space: NameSpaceXML, Local: "space"},
		Value: "preserve",
	}
	t.Space = ns
}
```

## How Has This Been Tested

* Microsoft Office 365 for Mac, 16.49 (21050901)
* Microsoft Office 2019 Professional Plus for Windows, 2105 (Build 14026.20302)
* Microsoft Office 2013 Professional Plus for Windows, 15.0.4919.1002

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by xuri** [comment]
Thanks for your PR. I have added the maximum character limit and escaped string literal conversion based on your PR, and only check prefix and suffix characters instead of  `strings.ContainsAny` will get better performance. This patch will be released in the next version.

**Comment by Arnie97** [comment]
I noticed that `strings.ContainsAny()` have visible impact on performance, but unfortunately...

1. The new patch did not fix the issue.  As clarified in #69, I would expect `"first line\nsecond line"` to be displayed correctly.  I'm still looking for better implementations that keeps the *`O(1)`* time complexity for a single cell though.
2. A much more critical factor is affecting the performance of `SetCellRichText()`, and that was my original motivation for this pull request. I've opened a separate issue for further discussions.

**Comment by xuri** [comment]
Note that don't forget to set the wrap text style for the cell with multi-line cell, for example

```go
f := excelize.NewFile()
styleID, err := f.NewStyle(&excelize.Style{Alignment: &excelize.Alignment{WrapText: true}})
if err != nil {
    fmt.Println(err)
}
if err := f.SetCellStyle("Sheet1", "A1", "A1", styleID); err != nil {
    fmt.Println(err)
}
if err := f.SetCellValue("Sheet1", "A1", "first line\nsecond line"); err != nil {
    fmt.Println(err)
}
```

**Comment by Arnie97** [comment]
Yes, you're right.  I've found that the `WrapText: true` style was later overwritten with another custom style in my code. Apologize for the misleading reply.

**Pull request merged**
